#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 2017/11/12 14:41
# @Author  : Jasontang
# @Site    : 
# @File    : test
# @ToDo    : 

import matplotlib.pyplot as plt
import numpy as np

if __name__ == '__main__':
	x1 = np.linspace(-1, 1, 300)
	y2 = 1 - (x1) ** 2
	y1 = np.log(y2)

	plt.subplot(211)
	plt.ylabel("ln(f(x))")
	plt.plot(x1, y1, '-')

	plt.subplot(212)
	plt.ylabel("f(x)")
	plt.plot(x1, y2, '-')

	plt.show()
